export type ItemType =
  | 'word'
  | 'phrase'
  | 'chunk'
  | 'idiom'
  | 'phrasal-verb'
  | 'collocation'

export type ItemStatus = 'inbox' | 'learning' | 'stable' | 'activation' | 'mastered'

/**
 * New 4-point learning level.
 *   0 = new       — never exposed
 *   1 = learning  — 1–2 exposures
 *   2 = familiar  — 3–7 exposures
 *   3 = mastered  — 8 exposures + sentence produced
 *
 * Stored alongside the legacy `status` field during the transition period.
 */
export type Level = 0 | 1 | 2 | 3

export type SourceType =
  | 'article'
  | 'podcast'
  | 'movie'
  | 'meeting'
  | 'email'
  | 'book'
  | 'other'

export type UsageChannel = 'speaking' | 'writing'

/**
 * Phase-6 fine-grained usage context.
 * Replaces the coarse UsageChannel for new logs.
 * Old logs keep `channel`; new logs set `context`.
 * Both are optional — usagePoints() counts any log that has either field.
 */
export type UsageContext =
  | 'work-email'
  | 'meeting'
  | 'conversation'
  | 'writing-practice'
  | 'note'
  | 'reading-listening'
  | 'other'

export type ReviewOutcome = 'again' | 'hard' | 'good' | 'easy'

export interface UsageLog {
  id: string
  usedAt: string
  /**
   * @deprecated Set by Phase-5 and earlier code.
   * New logs use `context` instead.  Kept for backward compatibility.
   */
  channel?: UsageChannel
  /** Fine-grained context introduced in Phase 6. */
  context?: UsageContext
  sentence?: string
  note?: string
  /** Learner's self-reported confidence (1 = unsure, 5 = fully natural). */
  confidence?: 1 | 2 | 3 | 4 | 5
}

export interface ReviewData {
  lastReviewedAt?: string
  nextReviewAt?: string
  intervalDays: number
  ease: number
  reviewCount: number
  successfulRecalls: number
  sentenceProduced: boolean
}

export interface ActivationData {
  requiredUses: number
  usageCount: number
  usageLogs: UsageLog[]
  /**
   * Learner's self-reported comfort level for using this word in real life.
   *   0 = not set (default)
   *   1 = not comfortable yet  (red)
   *   2 = somewhat comfortable (yellow)
   *   3 = comfortable / natural (green)
   *
   * Acts as an alternative mastery signal alongside usageCount and sentenceProduced.
   * Updated instantly via ConfidenceDots — no form required.
   */
  confidenceLevel?: 0 | 1 | 2 | 3
  /** ISO timestamp of the last time the learner updated their confidence level. */
  lastUsedAt?: string
}

export interface VocabItem {
  id: string
  term: string
  type: ItemType
  status: ItemStatus
  createdAt: string
  updatedAt: string

  sourceType?: SourceType
  sourceText?: string
  tags: string[]
  themes: string[]

  definitionEn?: string
  /** One-phrase (≤10 words) summary of the core meaning — generated by AI. */
  shortDefinition?: string
  translations?: {
    uk?: string
    pl?: string
    ru?: string
  }

  exampleSentence?: string
  workSentence?: string
  mySentence?: string

  synonyms: string[]
  antonyms: string[]
  nuance?: string
  register?: 'formal' | 'neutral' | 'conversational'
  commonMistakes?: string

  collocations: string[]
  sentenceFrames: string[]
  relatedPhrases: string[]

  etymology?: string
  memoryCue?: string

  review: ReviewData
  activation: ActivationData

  weeklyFocus: boolean
  /** ISO timestamp when the item was added to Focus This Week */
  focusAddedAt?: string
  /** Computed priority score — higher = kept longer on weekly reset */
  focusPriority?: number
  archived: boolean

  // ── Phase-1 new fields (added alongside legacy fields for compatibility) ───

  /** 4-point learning level derived from exposureCount + sentence production. */
  level?: Level

  /**
   * "My Current Focus" flag — supersedes weeklyFocus.
   * Both are written together during the transition; prefer inFocus in new code.
   */
  inFocus?: boolean

  /** Learner-specific difficulty score, 0–100 (higher = harder for this user). */
  difficultyScore?: number

  /** ISO timestamp of the most recent Daily Challenge exposure. */
  lastExposureAt?: string

  // ── AI enrichment ──────────────────────────────────────────────────────────
  // Set by addItem() and updated by enrichItem() in the store.
  // undefined = seed data (pre-populated, no generation needed)
  // 'pending'  = generation in progress
  // 'complete' = generation succeeded
  // 'failed'   = generation failed (see generationError)
  generationStatus?: 'pending' | 'complete' | 'failed'
  generationError?: string
  // Returned by the API alongside definitionEn and synonyms, etc.
  partOfSpeech?: string
  realLifeTask?: string

  // ── Daily Challenge SRS ─────────────────────────────────────────────────────
  // exposureCount tracks progress through 8 challenge steps (0 = new, 8 = mastered via challenge).
  // nextChallengeDate is set after each challenge exercise; undefined means due immediately.
  exposureCount?: number       // 0–8; undefined treated as 0
  nextChallengeDate?: string   // ISO datetime; undefined = due now

  // ── Related words (within the app's own vocabulary) ──────────────────────
  relatedEntries?: RelatedEntry[]
  relatedEntriesStatus?: 'pending' | 'complete' | 'failed'
  /** AI-suggested words not yet in the library that are worth adding */
  relatedSuggestions?: RelatedSuggestion[]
}

// ── Related words ─────────────────────────────────────────────────────────────

export type RelationshipType =
  | 'meaning'
  | 'usage_context'
  | 'nuance'
  | 'etymology'
  | 'word_family'
  | 'similar_form'
  | 'confusable'

export type RelationshipDirection =
  | 'synonym'
  | 'contrast'
  | 'same_family'
  | 'soundalike'
  | 'same_context'
  | 'confusable'

export interface RelatedEntry {
  id: string
  term: string
  relationshipType: RelationshipType
  direction?: RelationshipDirection
  /** 1 = weak, 2 = moderate, 3 = strong */
  strength: 1 | 2 | 3
  explanation: string
}

/** A related word that the learner does NOT yet have in their library */
export interface RelatedSuggestion {
  term: string
  type: ItemType
  relationshipType: RelationshipType
  direction?: RelationshipDirection
  /** One-line plain-English definition to show in the graph card */
  definitionHint: string
  explanation: string
}

export type VocabItemDraft = Pick<VocabItem, 'term' | 'type'> &
  Partial<
    Pick<
      VocabItem,
      | 'sourceType'
      | 'sourceText'
      | 'tags'
      | 'definitionEn'
      | 'status'
    >
  >

// ── Gamification ─────────────────────────────────────────────────────────────

export type BadgeId =
  | 'first-step'
  | 'on-a-roll'
  | 'week-warrior'
  | 'century'
  | 'grand-scholar'
  | 'early-bird'
  | 'diligent'

export interface Badge {
  id: BadgeId
  label: string
  description: string
  emoji: string
  unlockedAt?: string // ISO datetime
}

export type ExerciseType =
  | 'fill-blank'
  | 'multiple-choice'
  | 'synonym-match'
  | 'sentence-create'

/**
 * Phase-3 challenge types — drive which challenge component is shown and
 * how the attempt is recorded.  Escalates with exposureCount:
 *   0–1  → recognition / definition-choice
 *   2–4  → fill-gap / definition-choice
 *   5–7  → sentence-production
 *   8    → real-life-use-check (or sentence-production if not yet produced)
 */
export type ChallengeType =
  | 'recognition'
  | 'definition-choice'
  | 'fill-gap'
  | 'sentence-production'
  | 'real-life-use-check'

export interface ExerciseResult {
  itemId: string
  /** Supports both legacy ExerciseType and new ChallengeType values. */
  exerciseType: ExerciseType | ChallengeType
  points: number      // 0, 5, or 10
  userAnswer: string
  correct: boolean    // false for partial-credit sentence-production
  /** The correct answer to show in the feedback overlay when the user was wrong. */
  correctAnswer?: string
}

// ── AI Enrichment profile ─────────────────────────────────────────────────────
//
// Describes the structured JSON returned by /api/enrich.
// Fields that map directly to VocabItem are typed identically.
// Fields prefixed "suggested" are post-processing hints — they are NOT stored
// directly on VocabItem but are applied by enrichItem() in vocabStore.

export interface EnrichmentProfile {
  definitionEn?: string
  shortDefinition?: string
  partOfSpeech?: string
  register?: 'formal' | 'neutral' | 'conversational'
  nuance?: string
  synonyms?: string[]
  antonyms?: string[]
  collocations?: string[]
  sentenceFrames?: string[]
  relatedPhrases?: string[]
  exampleSentence?: string
  workSentence?: string
  commonMistakes?: string
  realLifeTask?: string
  etymology?: string
  memoryCue?: string
  /** AI-suggested kebab-case tags — auto-merged into item.tags after enrichment. */
  suggestedTags?: string[]
}

// ── Legacy stats ──────────────────────────────────────────────────────────────

export interface WeeklyStats {
  dueToday: number
  inboxCount: number
  inActivation: number
  masteredTotal: number
  weakItems: number
  usesLoggedThisWeek: number
  activatedThisWeek: number
  streak: number
  reviewedToday: number
}
