/**
 * NaturalPhrasesPage — Natural Phrases Sprint.
 *
 * Timed game (1 / 2 / 3 min).  One question type: given a word, pick the phrase
 * that uses it naturally.  The three wrong choices are deliberate learner-mistake
 * distractors generated by verb-swap / preposition-swap logic, not random other
 * words — making the discrimination meaningful at B2–C1 level.
 *
 * Phase flow: setup → playing → feedback → results
 * Gamification guardrails (CLAUDE.md): no XP, no streaks, objective counts only.
 * AI safety (CLAUDE.md): no AI calls at runtime, all questions generated locally.
 */

import { useState, useEffect, useRef, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  ArrowLeft, Link2, Timer, CheckCircle2, XCircle,
  ChevronRight, BookOpen, TrendingUp, Volume2, VolumeX,
  Pause, Play, Plus, Check, ExternalLink,
} from 'lucide-react'
import { playCorrectSound, playWrongSound, getSoundsEnabled, saveSoundsEnabled } from '@/lib/sounds'
import { useVocabStore }          from '@/store/vocabStore'
import { useNaturalPhrasesStore } from '@/store/naturalPhrasesStore'
import { usePracticeTimer }       from '@/hooks/usePracticeTimer'
import {
  buildPool, countScope, generateBatch,
  NATURAL_PHRASES_DURATIONS, NATURAL_PHRASES_DURATION_LABELS,
  type PoolEntry, type NaturalPhrasesQuestion, type NaturalPhrasesAttempt,
  type NaturalPhrasesScope, type NaturalPhrasesDuration,
} from '@/lib/naturalPhrasesGame'
import type { VocabItem } from '@/types/vocabulary'

// ── Types ──────────────────────────────────────────────────────────────────────

type Phase = 'setup' | 'playing' | 'paused' | 'feedback' | 'results'

interface FeedbackState {
  correct:             boolean
  correctCollocation:  string
  selectedIndex:       number
  isCrossLibrary:      boolean
  // Explore-panel data — fully captured at answer time, no runtime lookups needed
  anchorItemId:        string
  anchorTerm:          string
  anchorPartOfSpeech?: string
  anchorDef?:          string
  exampleSentence?:    string
  partnerItemId?:      string
  partnerTerm?:        string
  partnerPartOfSpeech?: string
  partnerDef?:         string
}

// ── Constants ──────────────────────────────────────────────────────────────────

const CORRECT_MS = 700
const BATCH_SIZE = 40

const SCOPE_LABELS: Record<NaturalPhrasesScope, string> = {
  focus: 'Focus words',
  full:  'All words',
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function formatTime(s: number): string {
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
}

// ── TimerBar ───────────────────────────────────────────────────────────────────

function TimerBar({ remaining, total }: { remaining: number; total: number }) {
  const pct    = total === 0 ? 0 : (remaining / total) * 100
  const urgent = remaining <= 10
  return (
    <div className="relative h-1.5 bg-slate-200 rounded-full overflow-hidden">
      <div
        className={`absolute inset-y-0 left-0 rounded-full transition-all duration-1000 ease-linear ${
          urgent ? 'bg-red-500' : 'bg-amber-500'
        }`}
        style={{ width: `${pct}%` }}
      />
    </div>
  )
}

// ── MissedList ─────────────────────────────────────────────────────────────────

function MissedList({
  attempts, items, addedIds, onAddToFocus, onNavigate,
}: {
  attempts:    NaturalPhrasesAttempt[]
  items:       VocabItem[]
  addedIds:    Set<string>
  onAddToFocus:(id: string) => void
  onNavigate:  (id: string) => void
}) {
  const missed = attempts
    .filter((a) => !a.wasCorrect)
    .filter((a, i, arr) => arr.findIndex((b) => b.itemId === a.itemId) === i)
  if (missed.length === 0) return null

  return (
    <div className="mb-4">
      <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">
        Missed — {missed.length} phrase{missed.length !== 1 ? 's' : ''}
      </p>
      <div className="bg-rose-50 border border-rose-200 rounded-xl overflow-hidden">
        {missed.map((a) => {
          const vocabItem = items.find((i) => i.id === a.itemId)
          const inFocus   = vocabItem?.inFocus || vocabItem?.weeklyFocus
          const added     = addedIds.has(a.itemId)
          return (
            <div key={a.itemId} className="flex items-center border-b border-rose-100 last:border-0">
              <button
                onClick={() => onNavigate(a.itemId)}
                className="flex-1 flex items-start gap-3 px-4 py-3 text-left hover:bg-rose-100 transition-colors"
              >
                <XCircle size={14} className="text-rose-400 shrink-0 mt-0.5" />
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-bold text-slate-800">{a.term}</p>
                  <p className="text-xs text-rose-600 line-through mt-0.5 truncate">
                    {a.optionPosition === 'after' ? `… ${a.givenOption}` : `${a.givenOption} …`}
                  </p>
                  <p className="text-xs text-emerald-700 font-medium mt-0.5 truncate">→ {a.correctCollocation}</p>
                </div>
                <ExternalLink size={12} className="text-rose-300 shrink-0 mt-0.5" />
              </button>
              {!inFocus && (
                <button
                  onClick={() => onAddToFocus(a.itemId)}
                  className={`mr-3 p-1.5 rounded-lg border transition-colors shrink-0 ${
                    added
                      ? 'bg-emerald-50 border-emerald-300 text-emerald-600'
                      : 'bg-white border-rose-200 text-rose-400 hover:text-amber-600 hover:border-amber-300 hover:bg-amber-50'
                  }`}
                  aria-label={added ? 'Added to Focus' : `Add ${a.term} to Focus`}
                >
                  {added ? <Check size={12} /> : <Plus size={12} />}
                </button>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ── ResultsView ────────────────────────────────────────────────────────────────

function ResultsView({
  correct, wrong, duration, scope,
  attemptsRef, items, addToFocus,
  startGame, navigate, setPhase,
}: {
  correct:     number
  wrong:       number
  duration:    NaturalPhrasesDuration
  scope:       NaturalPhrasesScope
  attemptsRef: React.MutableRefObject<NaturalPhrasesAttempt[]>
  items:       VocabItem[]
  addToFocus:  (ids: string[]) => Promise<{ added: number; evicted: number }>
  startGame:   () => void
  navigate:    ReturnType<typeof useNavigate>
  setPhase:    React.Dispatch<React.SetStateAction<Phase>>
}) {
  const [addedIds, setAddedIds] = useState<Set<string>>(new Set())
  const [selectedId, setSelectedId] = useState<string | null>(null)

  const total         = correct + wrong
  const accuracy      = total > 0 ? Math.round((correct / total) * 100) : 0
  const practiced     = new Set(attemptsRef.current.map((a) => a.itemId)).size
  const crossLibTotal = attemptsRef.current.filter((a) => a.isCrossLibrary).length
  const crossLibCorrect = attemptsRef.current.filter((a) => a.isCrossLibrary && a.wasCorrect).length

  const allResults     = useNaturalPhrasesStore.getState().results
  const durationHist   = allResults.filter((r) => r.durationSecs === duration)
  const prevBest       = durationHist.length > 1
    ? Math.max(...durationHist.slice(1).map((r) => r.correct))
    : null
  const isPersonalBest = total > 0 && prevBest !== null && correct > prevBest
  const durationLabel  = NATURAL_PHRASES_DURATION_LABELS[duration]

  function handleAddToFocus(itemId: string) {
    void addToFocus([itemId])
    setAddedIds((p) => new Set([...p, itemId]))
  }

  return (
    <div className="max-w-lg mx-auto px-4 py-6 pb-28 md:pb-10">
      <div className="flex items-center gap-3 mb-5">
        <button onClick={() => navigate(-1)}
          className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 transition-colors" aria-label="Go back">
          <ArrowLeft size={20} />
        </button>
        <h1 className="text-lg font-bold text-slate-900">{durationLabel} · done</h1>
      </div>

      {isPersonalBest && (
        <div className="mb-4 flex items-center gap-2 bg-emerald-50 border border-emerald-200 rounded-xl px-4 py-2.5">
          <TrendingUp size={14} className="text-emerald-600 shrink-0" />
          <p className="text-sm text-emerald-800">
            Personal best for {durationLabel} — up from {prevBest} correct.
          </p>
        </div>
      )}

      {/* Stats */}
      <div className="grid grid-cols-2 gap-3 mb-5">
        <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-4 text-center">
          <p className="text-3xl font-bold text-emerald-700 tabular-nums">{correct}</p>
          <p className="text-xs text-emerald-600 mt-1">Correct</p>
        </div>
        <div className="bg-rose-50 border border-rose-200 rounded-2xl p-4 text-center">
          <p className="text-3xl font-bold text-rose-600 tabular-nums">{wrong}</p>
          <p className="text-xs text-rose-500 mt-1">Wrong</p>
        </div>
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-center">
          <p className="text-3xl font-bold text-amber-700 tabular-nums">{accuracy}%</p>
          <p className="text-xs text-amber-600 mt-1">Accuracy</p>
        </div>
        <div className="bg-slate-50 border border-slate-200 rounded-2xl p-4 text-center">
          <p className="text-3xl font-bold text-slate-700 tabular-nums">{practiced}</p>
          <p className="text-xs text-slate-500 mt-1">Words seen</p>
        </div>
        {crossLibTotal > 0 && (
          <div className="col-span-2 bg-violet-50 border border-violet-200 rounded-2xl px-4 py-3 flex items-center justify-between">
            <div>
              <p className="text-sm font-semibold text-violet-800">Cross-vocabulary phrases</p>
              <p className="text-xs text-violet-500 mt-0.5">Questions where both words are in your library</p>
            </div>
            <p className="text-2xl font-bold text-violet-700 tabular-nums shrink-0 ml-3">
              {crossLibCorrect}<span className="text-sm font-normal text-violet-400">/{crossLibTotal}</span>
            </p>
          </div>
        )}
      </div>

      {/* Session history */}
      {durationHist.length > 0 && (
        <div className="mb-4 border border-slate-200 rounded-xl overflow-hidden">
          <div className="px-4 py-2 border-b border-slate-100">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">
              {durationLabel} — all sessions
            </p>
          </div>
          {durationHist.slice(0, 8).map((r, i) => (
            <div key={r.id} className={`flex items-center gap-3 px-4 py-2.5 text-xs ${i > 0 ? 'border-t border-slate-50' : ''}`}>
              <div className="flex-1 min-w-0">
                <span className="text-slate-700 font-medium">
                  {new Date(r.playedAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}
                </span>
                <span className="text-slate-400 ml-1.5">
                  {new Date(r.playedAt).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}
                </span>
              </div>
              <span className="font-semibold text-emerald-600 tabular-nums">{r.correct}✓</span>
              <span className="text-slate-400 tabular-nums">{r.accuracy}%</span>
            </div>
          ))}
        </div>
      )}

      {/* Missed phrases */}
      <MissedList
        attempts={attemptsRef.current}
        items={items}
        addedIds={addedIds}
        onAddToFocus={handleAddToFocus}
        onNavigate={setSelectedId}
      />

      {total === 0 && (
        <p className="text-sm text-slate-400 text-center mb-4">No questions answered — try again!</p>
      )}

      {/* Actions */}
      <div className="space-y-2.5">
        <button onClick={startGame}
          className="w-full flex items-center justify-center gap-2 py-3.5 bg-amber-500 hover:bg-amber-600 text-white text-sm font-bold rounded-2xl transition-colors">
          <Link2 size={15} />
          Play again · {durationLabel} · {SCOPE_LABELS[scope]}
        </button>
        <div className="flex gap-2.5">
          <button onClick={() => setPhase('setup')}
            className="flex-1 py-3 bg-white border border-slate-200 text-slate-700 text-sm font-semibold rounded-2xl hover:bg-slate-50 transition-colors">
            Change settings
          </button>
          <button onClick={() => navigate(-1)}
            className="flex-1 flex items-center justify-center gap-1.5 py-3 bg-slate-100 hover:bg-slate-200 text-slate-700 text-sm font-semibold rounded-2xl transition-colors">
            Done <ChevronRight size={14} />
          </button>
        </div>
      </div>

      {/* Quick word panel */}
      {selectedId && (
        <div className="fixed inset-0 z-40 flex items-end" onClick={() => setSelectedId(null)}>
          <div className="w-full max-w-lg mx-auto bg-white rounded-t-2xl shadow-2xl px-5 py-5 pb-10"
            onClick={(e) => e.stopPropagation()}>
            {(() => {
              const it = items.find((i) => i.id === selectedId)
              if (!it) return null
              return (
                <>
                  <p className="text-xl font-bold text-slate-900 mb-1">{it.term}</p>
                  {it.definitionEn && <p className="text-sm text-slate-600 leading-relaxed mb-3">{it.definitionEn}</p>}
                  {(it.collocations ?? []).length > 0 && (
                    <div className="mb-3">
                      <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wide mb-1.5">Collocations</p>
                      <div className="flex flex-wrap gap-1.5">
                        {it.collocations.map((c) => (
                          <span key={c} className="text-xs bg-amber-50 border border-amber-200 text-amber-800 px-2.5 py-1 rounded-full">{c}</span>
                        ))}
                      </div>
                    </div>
                  )}
                  <button onClick={() => navigate(`/item/${selectedId}`)}
                    className="w-full py-3 bg-brand-600 hover:bg-brand-700 text-white text-sm font-semibold rounded-xl transition-colors flex items-center justify-center gap-2 mt-2">
                    Open full detail <ExternalLink size={14} />
                  </button>
                </>
              )
            })()}
          </div>
        </div>
      )}
    </div>
  )
}

// ── NaturalPhrasesPage ─────────────────────────────────────────────────────────

export function NaturalPhrasesPage() {
  const navigate                              = useNavigate()
  const { items, recordExposure, addToFocus } = useVocabStore()
  const { addResult, saveLastSettings }       = useNaturalPhrasesStore()
  const pastResults  = useNaturalPhrasesStore((s) => s.results)
  const storedSettings = useRef({
    scope:    useNaturalPhrasesStore.getState().lastScope,
    duration: useNaturalPhrasesStore.getState().lastDuration,
  }).current
  const practiceTimer = usePracticeTimer('natural-phrases')

  // ── Settings ──────────────────────────────────────────────────────────────────
  const [scope,    setScope]    = useState<NaturalPhrasesScope>(storedSettings.scope)
  const [duration, setDuration] = useState<NaturalPhrasesDuration>(storedSettings.duration)
  const [soundOn,  setSoundOn]  = useState(getSoundsEnabled)

  const toggleSound = useCallback(() => {
    setSoundOn((p) => { saveSoundsEnabled(!p); return !p })
  }, [])

  // ── Phase ─────────────────────────────────────────────────────────────────────
  const [phase, setPhase] = useState<Phase>('setup')

  // ── Game state ────────────────────────────────────────────────────────────────
  const [timeLeft,   setTimeLeft]   = useState(0)
  const [questions,  setQuestions]  = useState<NaturalPhrasesQuestion[]>([])
  const [qIndex,     setQIndex]     = useState(0)
  const [correct,    setCorrect]    = useState(0)
  const [wrong,      setWrong]      = useState(0)
  const [feedback,     setFeedback]     = useState<FeedbackState | null>(null)
  const [showExplore,  setShowExplore]  = useState(false)

  const attemptsRef       = useRef<NaturalPhrasesAttempt[]>([])
  const gainedExposureRef = useRef<Set<string>>(new Set())
  const latestStats       = useRef({ correct: 0, wrong: 0 })
  const resultSaved       = useRef(false)
  const effectiveDuration = useRef<NaturalPhrasesDuration>(duration)
  const poolRef           = useRef<PoolEntry[]>([])

  // ── Save result ───────────────────────────────────────────────────────────────
  const saveResult = useCallback((finalCorrect: number, finalWrong: number) => {
    if (resultSaved.current) return
    resultSaved.current = true
    const total = finalCorrect + finalWrong
    addResult({
      id:             crypto.randomUUID(),
      playedAt:       new Date().toISOString(),
      durationSecs:   effectiveDuration.current,
      correct:        finalCorrect,
      wrong:          finalWrong,
      accuracy:       total > 0 ? Math.round((finalCorrect / total) * 100) : 0,
      wordsPracticed: new Set(attemptsRef.current.map((a) => a.itemId)).size,
      scope,
    })
    practiceTimer.finalize()
  }, [scope, addResult, practiceTimer])

  // ── Timer ─────────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (phase !== 'playing') return
    const id = setInterval(() => {
      setTimeLeft((t) => {
        if (t <= 1) {
          clearInterval(id)
          const { correct: c, wrong: w } = latestStats.current
          saveResult(c, w)
          setPhase('results')
          return 0
        }
        return t - 1
      })
    }, 1000)
    return () => clearInterval(id)
  }, [phase, saveResult])

  // ── Advance to next question ──────────────────────────────────────────────────
  const advanceToNext = useCallback(() => {
    setShowExplore(false)
    setFeedback(null)
    setQIndex((i) => i + 1)
    setPhase('playing')
  }, [])

  // ── Feedback auto-advance (correct only) ──────────────────────────────────────
  // Wrong answers require an explicit tap — the timer stays paused until the user
  // acknowledges the correct answer and clicks/taps to continue.
  useEffect(() => {
    if (phase !== 'feedback') return
    if (!feedback?.correct) return  // wrong: wait for user tap
    const id = setTimeout(advanceToNext, CORRECT_MS)
    return () => clearTimeout(id)
  }, [phase, feedback?.correct, advanceToNext])

  // ── Refill question queue ─────────────────────────────────────────────────────
  useEffect(() => {
    if (phase !== 'playing') return
    if (questions.length - qIndex >= 5) return
    const batch = generateBatch(poolRef.current, BATCH_SIZE)
    setQuestions((prev) => [...prev.slice(qIndex), ...batch])
    setQIndex(0)
  }, [qIndex, questions.length, phase])

  // ── Start game ────────────────────────────────────────────────────────────────
  const startGame = useCallback(() => {
    effectiveDuration.current = duration
    attemptsRef.current       = []
    gainedExposureRef.current = new Set()
    latestStats.current       = { correct: 0, wrong: 0 }
    resultSaved.current       = false
    practiceTimer.reset()
    setCorrect(0)
    setWrong(0)
    setFeedback(null)
    setQIndex(0)
    saveLastSettings(scope, duration)
    poolRef.current = buildPool(items, scope)
    const batch = generateBatch(poolRef.current, BATCH_SIZE)
    setQuestions(batch)
    setTimeLeft(duration)
    setPhase(batch.length === 0 ? 'results' : 'playing')
  }, [duration, scope, items, practiceTimer, saveLastSettings])

  const endGame = useCallback(() => {
    const { correct: c, wrong: w } = latestStats.current
    saveResult(c, w)
    setPhase('results')
  }, [saveResult])

  // ── Answer handler ────────────────────────────────────────────────────────────
  const handleAnswer = useCallback((choiceIndex: number) => {
    if (phase !== 'playing') return
    const q         = questions[qIndex]
    const isCorrect = choiceIndex === q.correctIndex

    attemptsRef.current.push({
      itemId:             q.itemId,
      term:               q.term,
      correctCollocation: q.correctCollocation,
      correctOption:      q.choices[q.correctIndex],
      givenOption:        q.choices[choiceIndex],
      wasCorrect:         isCorrect,
      optionPosition:     q.optionPosition,
      isCrossLibrary:     q.isCrossLibrary,
      partnerItemId:      q.partnerItemId,
    })

    if (soundOn) { isCorrect ? playCorrectSound() : playWrongSound() }

    if (isCorrect) {
      setCorrect((c) => { latestStats.current.correct = c + 1; return c + 1 })
      if (!gainedExposureRef.current.has(q.itemId)) {
        gainedExposureRef.current.add(q.itemId)
        void recordExposure(q.itemId, true)
      }
      // Award exposure to the partner library word too
      if (q.isCrossLibrary && q.partnerItemId && !gainedExposureRef.current.has(q.partnerItemId)) {
        gainedExposureRef.current.add(q.partnerItemId)
        void recordExposure(q.partnerItemId, true)
      }
    } else {
      setWrong((w) => { latestStats.current.wrong = w + 1; return w + 1 })
    }

    practiceTimer.bump({ advancement: isCorrect ? 1 : 0, itemId: q.itemId })

    // Capture explore-panel data at answer time so the overlay never needs
    // to look up items[] or depend on q being stable during render.
    const anchorItem  = items.find((i) => i.id === q.itemId)
    const partnerItem = q.partnerItemId ? items.find((i) => i.id === q.partnerItemId) : undefined

    setFeedback({
      correct:              isCorrect,
      correctCollocation:   q.correctCollocation,
      selectedIndex:        choiceIndex,
      isCrossLibrary:       q.isCrossLibrary,
      anchorItemId:         q.itemId,
      anchorTerm:           q.term,
      anchorPartOfSpeech:   q.partOfSpeech,
      anchorDef:            anchorItem?.definitionEn ?? (anchorItem as any)?.shortDefinition,
      exampleSentence:      q.exampleSentence ?? anchorItem?.exampleSentence,
      partnerItemId:        q.partnerItemId,
      partnerTerm:          partnerItem?.term,
      partnerPartOfSpeech:  partnerItem?.partOfSpeech,
      partnerDef:           partnerItem?.definitionEn ?? (partnerItem as any)?.shortDefinition,
    })
    setPhase('feedback')
  }, [phase, questions, qIndex, soundOn, recordExposure, practiceTimer, items])

  // ── Keyboard shortcuts ────────────────────────────────────────────────────────
  useEffect(() => {
    if (phase !== 'playing') return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') { endGame(); return }
      const n = parseInt(e.key, 10)
      if (n >= 1 && n <= 4) handleAnswer(n - 1)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [phase, handleAnswer, endGame])

  useEffect(() => {
    if (phase !== 'paused') return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape' || e.key === ' ') setPhase('playing')
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [phase])

  // Space / Enter / 1-4 advance past a wrong-answer feedback without auto-timer
  useEffect(() => {
    if (phase !== 'feedback' || feedback?.correct) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === ' ' || e.key === 'Enter' || (parseInt(e.key, 10) >= 1 && parseInt(e.key, 10) <= 4)) {
        e.preventDefault()
        advanceToNext()
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [phase, feedback?.correct, advanceToNext])

  // ── Results ───────────────────────────────────────────────────────────────────
  if (phase === 'results') {
    return (
      <ResultsView
        correct={correct}
        wrong={wrong}
        duration={effectiveDuration.current}
        scope={scope}
        attemptsRef={attemptsRef}
        items={items}
        addToFocus={addToFocus}
        startGame={startGame}
        navigate={navigate}
        setPhase={setPhase}
      />
    )
  }

  // ── Setup ─────────────────────────────────────────────────────────────────────
  if (phase === 'setup') {
    const focusCount   = countScope(items, 'focus')
    const fullCount    = countScope(items, 'full')
    const counts: Record<NaturalPhrasesScope, number> = { focus: focusCount, full: fullCount }
    const noWords      = fullCount < 4
    const tooFewScope  = counts[scope] < 4 && !(scope === 'focus' && fullCount >= 4)

    const totalSessions = pastResults.length
    const avgAccuracy   = totalSessions > 0
      ? Math.round(pastResults.reduce((s, r) => s + r.accuracy, 0) / totalSessions)
      : null

    return (
      <div className="max-w-lg mx-auto px-4 py-6 pb-28 md:pb-10">
        {/* Header */}
        <div className="flex items-center gap-3 mb-5">
          <button onClick={() => navigate(-1)}
            className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 transition-colors" aria-label="Go back">
            <ArrowLeft size={20} />
          </button>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-amber-500 flex items-center justify-center">
              <Link2 size={16} className="text-white" />
            </div>
            <h1 className="text-lg font-bold text-slate-900">Natural Phrases Sprint</h1>
          </div>
          {totalSessions > 0 && (
            <div className="ml-auto flex items-center gap-3 text-xs text-slate-400">
              <span>{totalSessions} session{totalSessions !== 1 ? 's' : ''}</span>
              {avgAccuracy !== null && <span>{avgAccuracy}% avg</span>}
            </div>
          )}
        </div>

        {/* Scope picker */}
        <div className="mb-5">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Word selection</p>
          <div className="grid grid-cols-2 gap-2">
            {(['focus', 'full'] as NaturalPhrasesScope[]).map((s) => {
              const cnt      = counts[s]
              const isActive = scope === s
              const disabled = cnt < 4
              const sub      = s === 'focus'
                ? (cnt > 0 ? `${cnt} focus word${cnt !== 1 ? 's' : ''} with collocations` : 'None with collocations')
                : `${cnt} word${cnt !== 1 ? 's' : ''} with collocations`
              return (
                <button key={s} onClick={() => !disabled && setScope(s)} disabled={disabled} aria-pressed={isActive}
                  className={`px-3 py-3 rounded-xl border text-sm font-semibold text-left transition-colors disabled:cursor-not-allowed ${
                    isActive
                      ? 'bg-amber-500 text-white border-amber-500'
                      : disabled
                      ? 'bg-slate-50 text-slate-400 border-slate-200'
                      : 'bg-white text-slate-700 border-slate-200 hover:border-amber-300 hover:bg-amber-50'
                  }`}>
                  <span className="block">{SCOPE_LABELS[s]}</span>
                  <span className={`text-xs font-normal mt-0.5 block ${isActive ? 'text-amber-100' : disabled ? 'text-slate-300' : 'text-slate-400'}`}>
                    {sub}
                  </span>
                </button>
              )
            })}
          </div>
          {scope === 'focus' && focusCount < 4 && fullCount >= 4 && (
            <p className="mt-2 text-xs text-amber-600 flex items-center gap-1.5">
              <BookOpen size={12} className="shrink-0" />
              Fewer than 4 focus words with collocations — will use full vocabulary instead.
            </p>
          )}
        </div>

        {noWords && (
          <div className="mb-5 flex items-start gap-2.5 bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 text-sm text-amber-800">
            <BookOpen size={15} className="shrink-0 mt-0.5 text-amber-600" />
            <p>You need at least 4 words with collocations filled in. Add collocations to your vocabulary words to play.</p>
          </div>
        )}

        {/* Duration picker */}
        <div className="mb-5">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Duration</p>
          <div className="grid grid-cols-3 gap-2">
            {NATURAL_PHRASES_DURATIONS.map((d) => {
              const history  = pastResults.filter((r) => r.durationSecs === d)
              const best     = history.length > 0 ? Math.max(...history.map((r) => r.correct)) : null
              const isActive = duration === d
              return (
                <button key={d} onClick={() => setDuration(d)}
                  className={`py-3 px-2 rounded-xl text-sm font-semibold border transition-colors flex flex-col items-center gap-0.5 ${
                    isActive
                      ? 'bg-amber-500 text-white border-amber-500'
                      : 'bg-white text-slate-700 border-slate-200 hover:border-amber-300 hover:bg-amber-50'
                  }`}>
                  <span>{NATURAL_PHRASES_DURATION_LABELS[d]}</span>
                  {best !== null && (
                    <span className={`text-[10px] font-normal ${isActive ? 'text-amber-100' : 'text-slate-400'}`}>
                      best {best}✓
                    </span>
                  )}
                </button>
              )
            })}
          </div>
        </div>

        {/* Session history */}
        {pastResults.length > 0 && (
          <div className="mb-5">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Recent sessions</p>
            <div className="border border-slate-200 rounded-xl overflow-hidden">
              {pastResults.slice(0, 6).map((r, i) => (
                <div key={r.id} className={`flex items-center gap-3 px-4 py-2.5 text-xs ${i > 0 ? 'border-t border-slate-100' : ''}`}>
                  <div className="flex-1 min-w-0">
                    <span className="text-slate-700 font-medium">
                      {new Date(r.playedAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}
                    </span>
                    <span className="text-slate-400 ml-1.5">
                      {new Date(r.playedAt).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                  <span className="text-slate-400 shrink-0">{NATURAL_PHRASES_DURATION_LABELS[r.durationSecs as NaturalPhrasesDuration]}</span>
                  <span className="font-semibold text-emerald-600 tabular-nums shrink-0">{r.correct}✓</span>
                  <span className="text-slate-400 tabular-nums shrink-0">{r.accuracy}%</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* What to expect */}
        <div className="mb-6 space-y-1.5 text-xs text-slate-400">
          <p>· A word is shown — pick the phrase that uses it naturally</p>
          <p>· <span className="font-mono text-slate-500">… option</span> means the word comes first (e.g. <span className="font-mono">overcome … adversity</span>)</p>
          <p>· <span className="font-mono text-slate-500">option …</span> means the word comes after (e.g. <span className="font-mono">maintain … vigilance</span>)</p>
          <p>· Many phrases pair two vocabulary words — answering correctly trains both</p>
          <p>· Wrong options are real learner mistakes — wrong verb, wrong preposition</p>
          <p>· First correct answer per word adds one exposure</p>
          <p>· Press <kbd className="font-mono bg-slate-100 border border-slate-300 rounded px-1 py-0.5 text-slate-600">1</kbd>–<kbd className="font-mono bg-slate-100 border border-slate-300 rounded px-1 py-0.5 text-slate-600">4</kbd> to answer · <kbd className="font-mono bg-slate-100 border border-slate-300 rounded px-1 py-0.5 text-slate-600">Esc</kbd> to end</p>
        </div>

        <button onClick={startGame} disabled={noWords || tooFewScope}
          className="w-full py-3.5 bg-amber-500 hover:bg-amber-600 disabled:opacity-40 text-white text-sm font-bold rounded-2xl transition-colors flex items-center justify-center gap-2">
          <Link2 size={16} />
          Start · {NATURAL_PHRASES_DURATION_LABELS[duration]} · {SCOPE_LABELS[scope]}
        </button>
      </div>
    )
  }

  // ── Playing / paused / feedback ───────────────────────────────────────────────
  const q = questions[qIndex]
  if (!q) {
    return (
      <div className="max-w-lg mx-auto px-4 py-6 text-center">
        <p className="text-slate-500 text-sm">Loading…</p>
      </div>
    )
  }

  const urgent = timeLeft <= 10

  return (
    <div className="max-w-lg mx-auto px-4 py-4 pb-28 md:pb-8 flex flex-col min-h-screen">

      {/* Top bar */}
      <div className="mb-4 space-y-1.5">
        <div className="flex items-center gap-3">
          <button onClick={endGame}
            className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 transition-colors" aria-label="End game">
            <ArrowLeft size={20} />
          </button>

          {/* Timer */}
          <div className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl font-mono text-sm font-bold ${
            urgent ? 'bg-red-50 text-red-600' : 'bg-slate-100 text-slate-700'
          }`}>
            <Timer size={14} className={urgent ? 'animate-pulse' : ''} />
            {formatTime(timeLeft)}
          </div>

          <div className="flex-1">
            <TimerBar remaining={timeLeft} total={effectiveDuration.current} />
          </div>

          {/* Pause */}
          {phase === 'playing' && (
            <button onClick={() => setPhase('paused')}
              className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-400 transition-colors shrink-0" aria-label="Pause">
              <Pause size={16} />
            </button>
          )}
          {phase === 'paused' && (
            <button onClick={() => setPhase('playing')}
              className="p-1.5 rounded-lg bg-amber-50 hover:bg-amber-100 text-amber-600 transition-colors shrink-0" aria-label="Resume">
              <Play size={16} />
            </button>
          )}

          <button onClick={toggleSound}
            className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-400 transition-colors shrink-0"
            aria-label={soundOn ? 'Mute' : 'Enable sound'}>
            {soundOn ? <Volume2 size={16} /> : <VolumeX size={16} />}
          </button>
        </div>

        {/* Score row */}
        <div className="flex items-center gap-2 px-0.5 text-xs font-semibold">
          <span className="text-emerald-600 tabular-nums">{correct}✓</span>
          <span className="text-slate-300">·</span>
          <span className="text-rose-500 tabular-nums">{wrong}✗</span>
          {(correct + wrong) > 0 && (
            <>
              <span className="text-slate-300">·</span>
              <span className="text-slate-500 tabular-nums">
                {Math.round((correct / (correct + wrong)) * 100)}%
              </span>
            </>
          )}
        </div>
      </div>

      {/* Question card */}
      <div className={`rounded-2xl border-2 p-5 mb-4 transition-colors ${
        phase === 'feedback'
          ? feedback?.correct ? 'bg-emerald-50 border-emerald-300' : 'bg-rose-50 border-rose-300'
          : phase === 'paused' ? 'bg-slate-50 border-slate-200 select-none'
          : 'bg-white border-slate-200'
      }`}>
        <p className="text-[10px] font-semibold text-amber-500 uppercase tracking-wider mb-3">
          Pick the natural phrase
        </p>

        <div className={phase === 'paused' ? 'blur-sm pointer-events-none' : ''}>
          {/* Term */}
          <p className="text-3xl font-bold text-slate-900 leading-none mb-1">{q.term}</p>
          {q.partOfSpeech && (
            <p className="text-xs text-slate-400 italic mb-1">{q.partOfSpeech}</p>
          )}
          {q.definitionEn && (
            <p className="text-sm text-slate-500 leading-relaxed line-clamp-2 mb-2">{q.definitionEn}</p>
          )}
          {/* Slot context — shows where the word fits in the phrase */}
          <p className="text-sm font-mono text-amber-600/70 tracking-wide">
            {q.optionPosition === 'after' ? `${q.term} ___` : `___ ${q.term}`}
          </p>
        </div>

        {/* Feedback banner */}
        {phase === 'feedback' && feedback && (
          feedback.correct ? (
            <div className="mt-4 rounded-xl bg-emerald-100 text-emerald-700">
              <div className="flex items-center gap-2 px-3 py-2.5 text-sm font-semibold">
                <CheckCircle2 size={16} /> Correct!
              </div>
              {feedback.isCrossLibrary && (
                <p className="px-3 pb-2.5 text-xs text-emerald-600">
                  You practised two vocabulary words at once.
                </p>
              )}
            </div>
          ) : (
            <div className="mt-4 rounded-xl bg-rose-100 text-rose-800">
              <div className="flex items-start gap-2 px-3 py-2.5 text-sm font-semibold">
                <XCircle size={16} className="shrink-0 mt-0.5" />
                <span>The natural phrase is: <strong>{feedback.correctCollocation}</strong></span>
              </div>
              {feedback.isCrossLibrary && (
                <p className="px-3 pb-2 text-xs text-rose-600">
                  Both words are in your vocabulary — practice them together.
                </p>
              )}
              <div className="flex border-t border-rose-200">
                <button
                  onClick={() => setShowExplore(true)}
                  className="flex-1 py-2.5 text-sm font-semibold text-rose-600 hover:bg-rose-200 active:bg-rose-300 transition-colors flex items-center justify-center gap-1.5"
                >
                  <BookOpen size={13} /> Explore phrase
                </button>
                <button
                  onClick={advanceToNext}
                  className="flex-1 py-2.5 text-sm font-bold text-rose-700 border-l border-rose-200 hover:bg-rose-200 active:bg-rose-300 transition-colors rounded-br-xl"
                >
                  Continue →
                </button>
              </div>
            </div>
          )
        )}
      </div>

      {/* Choices */}
      <div className={`grid grid-cols-1 gap-2 ${phase === 'paused' ? 'blur-sm pointer-events-none select-none' : ''}`}>
        {q.choices.map((choice, idx) => {
          const isCorrect   = phase === 'feedback' && idx === q.correctIndex
          const isWrong     = phase === 'feedback' && !feedback?.correct && idx === feedback?.selectedIndex
          // "…" marks where the target word sits relative to the collocating part
          const displayText = q.optionPosition === 'after' ? `… ${choice}` : `${choice} …`
          return (
            <button key={idx} onClick={() => handleAnswer(idx)}
              disabled={phase === 'feedback' || phase === 'paused'}
              className={`w-full text-left px-4 py-3.5 rounded-xl border text-sm font-medium transition-colors disabled:cursor-default ${
                isCorrect
                  ? 'bg-emerald-100 border-emerald-400 text-emerald-800'
                  : isWrong
                  ? 'bg-rose-100 border-rose-400 text-rose-700'
                  : phase === 'feedback'
                  ? 'bg-slate-50 border-slate-200 text-slate-400'
                  : 'bg-white border-slate-200 text-slate-800 hover:border-amber-400 hover:bg-amber-50 active:scale-[0.99]'
              }`}>
              <span className="inline-flex items-center gap-2.5">
                <span className={`w-5 h-5 rounded-full border text-[10px] font-bold flex items-center justify-center shrink-0 ${
                  phase === 'playing'
                    ? 'border-slate-300 text-slate-400'
                    : isCorrect ? 'bg-emerald-500 border-emerald-500 text-white'
                    : isWrong   ? 'bg-rose-400 border-rose-400 text-white'
                    : 'border-slate-200 text-slate-300'
                }`}>{idx + 1}</span>
                {displayText}
              </span>
            </button>
          )
        })}
      </div>

      {/* Pause overlay */}
      {phase === 'paused' && (
        <div className="fixed inset-0 z-50 flex flex-col items-center justify-center gap-5 bg-slate-900/70 backdrop-blur-sm">
          <p className="text-white text-xl font-bold">Paused</p>
          <button onClick={() => setPhase('playing')}
            className="flex items-center gap-2 px-8 py-3.5 bg-white text-slate-900 rounded-2xl font-bold text-sm hover:bg-slate-50 transition-colors">
            <Play size={16} /> Resume
          </button>
          <button onClick={endGame} className="text-xs text-white/50 hover:text-white/80 transition-colors">End session</button>
          <p className="text-xs text-white/40">Press Esc or Space to resume</p>
        </div>
      )}

      {/* Explore phrase overlay — shown after a wrong answer */}
      {showExplore && feedback && (
        <div
          className="fixed inset-0 z-50 flex items-end justify-center pb-16 md:pb-0"
          onClick={() => setShowExplore(false)}
        >
          <div
            className="w-full max-w-lg bg-white rounded-t-2xl shadow-2xl px-5 pt-5 pb-6 max-h-[75vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Phrase headline */}
            <p className="text-[10px] font-semibold text-rose-400 uppercase tracking-wider mb-1">Natural phrase</p>
            <p className="text-2xl font-bold text-slate-900 mb-4">{feedback.correctCollocation}</p>

            {/* Anchor word */}
            <div className="mb-3">
              <p className="text-xs font-semibold text-slate-500 mb-0.5">
                {feedback.anchorTerm}{feedback.anchorPartOfSpeech ? ` · ${feedback.anchorPartOfSpeech}` : ''}
              </p>
              {feedback.anchorDef && (
                <p className="text-sm text-slate-700 leading-relaxed">{feedback.anchorDef}</p>
              )}
            </div>

            {/* Partner word (cross-library) */}
            {feedback.partnerTerm && (
              <div className="mb-3 pl-3 border-l-2 border-violet-200">
                <p className="text-xs font-semibold text-slate-500 mb-0.5">
                  {feedback.partnerTerm}{feedback.partnerPartOfSpeech ? ` · ${feedback.partnerPartOfSpeech}` : ''}
                  <span className="ml-1.5 text-violet-500 font-normal">also in your vocabulary</span>
                </p>
                {feedback.partnerDef && (
                  <p className="text-sm text-slate-700 leading-relaxed">{feedback.partnerDef}</p>
                )}
              </div>
            )}

            {/* Example sentence */}
            {feedback.exampleSentence && (
              <div className="mb-4 bg-amber-50 border border-amber-200 rounded-xl px-3 py-2.5">
                <p className="text-[10px] font-semibold text-amber-500 uppercase tracking-wider mb-1">Example</p>
                <p className="text-sm text-amber-900 leading-relaxed italic">
                  "{feedback.exampleSentence}"
                </p>
              </div>
            )}

            {/* Actions */}
            <div className="flex gap-2.5">
              <button
                onClick={() => { navigate(`/item/${feedback.anchorItemId}`); setShowExplore(false) }}
                className="flex-1 py-3 border border-slate-200 text-slate-600 text-sm font-semibold rounded-xl hover:bg-slate-50 transition-colors flex items-center justify-center gap-1.5"
              >
                <ExternalLink size={13} /> Full detail
              </button>
              <button
                onClick={advanceToNext}
                className="flex-1 py-3 bg-amber-500 hover:bg-amber-600 text-white text-sm font-bold rounded-xl transition-colors"
              >
                Back to game →
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
